services:
  dashboard:
    build: .
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - .:/app

  scheduler:
    build: .
    command: python scheduler.py
    volumes:
      - .:/app